### ISSUE TITLE
Help with implementing sort.

### ISSUE THREAD

**Issue by ThatOneCubanDude** [Federico-abss/CS50-intro-course#2]
https://github.com/Federico-abss/CS50-intro-course/blob/042a21e3574feec2384d46d2d0bc08067f26435c/C/pset3/tideman/tideman.c#L154-L168

Hi, I am also doing this project and I've been stuck specifically on this sort function for a few days. I know your implementation works but I'm quite new to coding and I don't really understand it. I was wondering if you could show me a different way to sort the pairs without making a new function and using pointers to get the difference in margins of victory between pairs. I know how to sort it but I don't know how to get the margins so I can sort them.

*Also sorry for posting this as an Issue, I was trying to find out how to leave a comment underneath your code but I couldn't figure it out. I'm new to GitHub too :/

**Comment by Federico-abss** [comment]
Hey man, the problem is that this is the way that qsort works, you need to use pointers to have it functional, you could try see if there are other sort functions that work the way you want them to but I doubt it. 
The best advice I can give is watching the lesson that deals with pointers and then come back with a better understanding. 

Inviato da Yahoo Mail su Android 
 
  Il ven, 3 apr, 2020 alle 6:04, ThatOneCubanDude<notifications@github.com> ha scritto:   


https://github.com/Federico-abss/CS50-intro-course/blob/042a21e3574feec2384d46d2d0bc08067f26435c/C/pset3/tideman/tideman.c#L154-L168

Hi, I am also doing this project and I've been stuck specifically on this sort function for a few days. I know your implementation works but I'm quite new to coding and I don't really understand it. I was wondering if you could show me a different way to sort the pairs without making a new function and using pointers to get the difference in margins of victory between pairs. I know how to sort it but I don't know how to get the margins so I can sort them.

*Also sorry for posting this as an Issue, I was trying to find out how to leave a comment underneath your code but I couldn't figure it out. I'm new to GitHub too :/

**Comment by ThatOneCubanDude** [comment]
Ok, I might skip this one for a while and then come back to it as you suggested. Do you know any other way I could get the margins for all the pairs without using pointers? 

This is what I have right now but it doesn't work according to check50:

```
// Sort pairs in decreasing order by strength of victory
void sort_pairs(void)
{   
    for (int j = 0; j < pair_count; j++)
    {
        for (int i = 0; i < pair_count - j - 1; i++)
        {
            int margin = pairs[i].winner - pairs[i].loser;
            int margin_next = pairs[i+1].winner - pairs[i+1].loser;
            
            pair tmp[1];
            
            if (margin < margin_next)
            {
                tmp[0] = pairs[i];
                pairs[i] = pairs[i+1];
                pairs[i+1] = tmp[0];
            }
        }
    }
    return;
}
```

**Comment by Federico-abss** [comment]
Getting the margins is not difficult, you are doing it right, is the implementation of a sorting function that it is very complicated since it necessarily requires pointers. When you see the lesson you will understand how it works. 

Inviato da Yahoo Mail su Android 
 
  Il ven, 3 apr, 2020 alle 8:04, ThatOneCubanDude<notifications@github.com> ha scritto:   


Ok, I might skip this one for a while and then come back to it as you suggested. Do you know any other way I could get the margins for all the pairs without using pointers?

This is what I have right now but it doesn't work according to check50:

// Sort pairs in decreasing order by strength of victory
void sort_pairs(void)
{
for (int j = 0; j < pair_count; j++)
{
for (int i = 0; i < pair_count - j - 1; i++)
{
int margin = pairs[i].winner - pairs[i].loser;
int margin_next = pairs[i+1].winner - pairs[i+1].loser;
        pair tmp[1];
        
        if (margin < margin_next)
        {
            tmp[0] = pairs[i];
            pairs[i] = pairs[i+1];
            pairs[i+1] = tmp[0];
        }
    }
}
return;

}
